name: Feature request
about: Suggest an idea for this project
labels: "feature"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your time helping COB Chatbot improve!

  - type: textarea
      attributes:
        label: Description
        description: Please describe the feature you want us to add.
        placeholder: Start by adding...
      validations:
        required: true